# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d24fdfc2af08343c478e42c2a69b044c243f6892c5911c94bb6a18cd2f96aab7dbfc6cddc9ab45e561f39cc937eb61c5b3811722fd58646ed97f3263373b97

test:
  secret_key_base: 7fd18912302dca6b5af68f89c5a7c4f85988d83eb95a3a3fa175a5e1a6fb978a3bcdb98f069cc73ee37afb10cf9f0ebc6b25637fbdc7eafbac0f048ad783851a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
